# Generated by Django 5.0.1 on 2024-01-31 00:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='hero_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='thumbnail/img/portfolios/hero/'),
            preserve_default=False,
        ),
    ]
