# Generated by Django 5.0.1 on 2024-01-31 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0002_portfolio_hero_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociallink',
            name='url',
            field=models.CharField(max_length=255),
        ),
    ]
